# Generated by Django 3.0.6 on 2020-05-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tB', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default='Dummy_User', max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='user',
            field=models.CharField(max_length=15),
        ),
    ]
