# Generated by Django 3.0.6 on 2020-05-14 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tB', '0002_auto_20200515_0332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='data',
            new_name='user_link',
        ),
    ]
